### ISSUE TITLE
Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by volcverse** [fdlm/listening-moods#2]
Hello. I got a problem when I run the code.
Cannot load file containing pickled data when allow_pickle=False
after I change the code in run.py 25th line to: features = np.load(join(DATA_DIR, f'{feature}_source.npy'),allow_pickle=True)
I got:
OSError: Failed to interpret file 'data/mcn_msd_big_source.npy' as a pickle

How to solve this? Any response will be greatly appreciated! :)

**Comment by urinieto** [comment]
Hi! The npy file you're trying to open is actually stored on [git LFS](https://git-lfs.github.com/). To download it, you have to install Git LFS, and then delete the files, and check them out again. Basically (on macOS):

    brew install git-lfs
    git lfs install
    rm data/*npy
    git checkout .
    
However, **this doesn't work because our Git LFS maxed out our quota**! @fdlm , is there anything I can do to increase this? I don't seem to have writing access to that Git LFS repo.

Thanks for reporting, @DummyNodeHead !

**Comment by fdlm** [comment]
Ah, thanks for catching this. I uploaded the data files [here](https://drive.google.com/file/d/1ecA1N1Mp1mOpwbntfWNQIMMrwPBrYzvl/view?usp=sharing), so you can grab them and put them in the right directory.
